export const movie = [
   {
    id: 1,
    name: 1
   },
   {
    id: 2,
    name: 2
   },
   {
    id: 3,
    name: 3
   },
   {
    id: 4,
    name: 4
   },
   {
    id: 5,
    name: 5
   },
   {
    id: 6,
    name: 6
   },
   {
    id: 7,
    name: 7
   },
   {
    id: 8,
    name: 8
   },
   {
    id: 9,
    name: 9
   },
   {
    id: 10,
    name: 10
   },
   {
    id: 11,
    name: 11
   },
   {
    id: 12,
    name: 12
   },

];

export const movie2 = [
    {
     id: 1,
     name: 12
    },
    {
     id: 2,
     name: 22
    },
    {
     id: 3,
     name: 32
    },
    {
     id: 4,
     name: 42
    },
    {
     id: 5,
     name: 52
    },
    {
     id: 6,
     name: 62
    },
    {
     id: 7,
     name: 72
    },
    {
     id: 8,
     name: 82
    },
    {
     id: 9,
     name: 92
    },
    {
     id: 10,
     name: 102
    },
    {
     id: 11,
     name: 112
    },
    {
     id: 12,
     name: 122
    },
 
 ];
 
 